import { Transaction } from "@/types/declaration";

export const dummyTransactionHistory: Transaction[] = [
  {
    id: 1,
    category: "Food",
    note: "Lunch",
    type: "expense",
    amount: 100,
    date: "August 12 - 12:00 PM",
  },
  {
    id: 2,
    category: "Transport",
    note: "Bus",
    type: "expense",
    amount: 50,
    date: "August 12 - 12:00 PM",
  },
  {
    id: 3,
    category: "Salary",
    note: "Monthly Salary",
    type: "income",
    amount: 1000,
    date: "August 12 - 12:00 PM",
  },
  {
    id: 4,
    category: "Food",
    note: "Dinner",
    type: "expense",
    amount: 150,
    date: "August 12 - 12:00 PM",
  },
  {
    id: 5,
    category: "Transport",
    note: "Bus",
    type: "expense",
    amount: 50,
    date: "August 12 - 12:00 PM",
  },
  {
    id: 6,
    category: "Salary",
    note: "Monthly Salary",
    type: "income",
    amount: 1000,
    date: "August 12 - 12:00 PM",
  },
  {
    id: 7,
    category: "Food",
    note: "Lunch",
    type: "expense",
    amount: 100,
    date: "August 12 - 12:00 PM",
  },
  {
    id: 8,
    category: "Transport",
    note: "Bus",
    type: "expense",
    amount: 50,
    date: "August 12 - 12:00 PM",
  },
  {
    id: 9,
    category: "Salary",
    note: "Monthly Salary",
    type: "income",
    amount: 1000,
    date: "August 12 - 12:00 PM",
  },
  {
    id: 10,
    category: "Food",
    note: "Dinner",
    type: "expense",
    amount: 150,
    date: "August 12 - 12:00 PM",
  },
  {
    id: 11,
    category: "Transport",
    note: "Bus",
    type: "expense",
    amount: 50,
    date: "August 12 - 12:00 PM",
  },
  {
    id: 12,
    category: "Salary",
    note: "Monthly Salary",
    type: "income",
    amount: 1000,
    date: "August 12 - 12:00 PM",
  },
  {
    id: 13,
    category: "Food",
    note: "Lunch",
    type: "expense",
    amount: 100,
    date: "August 12 - 12:00 PM",
  },
  {
    id: 14,
    category: "Transport",
    note: "Bus",
    type: "expense",
    amount: 50,
    date: "August 12 - 12:00 PM",
  },
  {
    id: 15,
    category: "Salary",
    note: "Monthly Salary",
    type: "income",
    amount: 1000,
    date: "August 12 - 12:00 PM",
  },
  {
    id: 16,
    category: "Food",
    note: "Dinner",
    type: "expense",
    amount: 150,
    date: "August 12 - 12:00 PM",
  },
  {
    id: 17,
    category: "Transport",
    note: "Bus",
    type: "expense",
    amount: 50,
    date: "August 12 - 12:00 PM",
  },
  {
    id: 18,
    category: "Salary",
    note: "Monthly Salary",
    type: "income",
    amount: 1000,
    date: "August 12 - 12:00 PM",
  },
  {
    id: 19,
    category: "Food",
    note: "Lunch",
    type: "expense",
    amount: 100,
    date: "August 12 - 12:00 PM",
  },
  {
    id: 20,
    category: "Transport",
    note: "Bus",
    type: "expense",
    amount: 50,
    date: "August 12 - 12:00 PM",
  },
  {
    id: 21,
    category: "Salary",
    note: "Monthly Salary",
    type: "income",
    amount: 1000,
    date: "August 12 - 12:00 PM",
  },
];
